#line 2 "lexic.cpp"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.85 95/04/24 10:48:47 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>


/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 126
#define YY_END_OF_BUFFER 127
static yyconst short int yy_accept[359] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,  127,  125,
      122,  124,   80,    4,   77,  109,  101,    3,  116,  117,
      107,  110,  113,  111,  112,  108,    2,  114,  123,   83,
       98,   84,  115,  118,  119,  102,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,  120,  100,  121,   99,   17,   16,   17,    8,
        7,    5,    8,   12,   11,    9,   12,   79,   77,   77,
       94,   81,   95,    0,   92,  105,   89,  106,   90,    2,
       14,   13,   93,    2,    2,    0,  103,   85,   78,   86,
      104,   97,   77,   77,   77,   77,   77,   77,   77,   77,

       77,   77,   31,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   44,   77,   47,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   96,   82,   15,    6,   10,
       91,   13,   13,    2,    0,    2,  103,   88,   87,  104,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   41,   77,   77,   77,   77,   49,   77,   77,   53,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   70,   77,   72,   77,   77,

       77,   77,   77,   77,   77,   21,   22,   77,   24,   77,
       77,   77,   77,   77,   77,   77,   77,   33,   34,   77,
       77,   77,   77,   77,   77,   43,   77,   77,   77,   77,
       51,   77,   54,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   65,   77,   77,   69,   77,   73,   77,
       77,   76,   77,   77,   20,   23,   25,   26,   77,   77,
       77,   77,    1,   77,   77,   77,   37,   38,   40,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       60,   77,   62,   77,   77,   66,   77,   77,   77,   75,
       77,   77,   77,   77,   77,   30,   32,   35,   77,   77,

       77,   77,   46,   77,   77,   52,   77,   77,   77,   58,
       59,   61,   63,   77,   67,   77,   71,   77,   77,   19,
       77,   77,   29,   36,   39,   77,   77,   77,   77,   55,
       56,   77,   77,   77,   77,   18,   27,   28,   42,   77,
       77,   77,   77,   77,   77,   74,   77,   77,   50,   57,
       77,   68,   45,   48,   77,   77,   64,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    6,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   19,   20,   21,
       22,   23,   24,    1,    6,    6,    6,    6,   25,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
       26,   27,   28,   29,    6,    1,   30,   31,   32,   33,

       34,   35,   36,   37,   38,    6,   39,   40,   41,   42,
       43,   44,    6,   45,   46,   47,   48,   49,   50,   51,
       52,   53,   54,   55,   56,   57,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[58] =
    {   0,
        1,    1,    1,    1,    1,    2,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    2,    1,    1,
        1,    1,    1,    1,    2,    1,    1,    1,    1,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[365] =
    {   0,
        0,    0,   55,   56,   57,   60,   59,   67,  656,  657,
      657,  657,  633,  657,  636,  631,   53,  657,  657,  657,
       59,   52,  657,   58,  634,   66,   73,  657,  657,   55,
      629,   70,  657,  657,  657,  628,   64,   61,   72,   67,
       78,   93,   79,  103,   81,   98,  107,   85,  112,   90,
       96,  116,  657,   95,  657,  657,  657,  657,  632,  657,
      657,  657,  639,  657,  657,  657,  642,  657,  628,    0,
      657,  657,  657,  623,  657,  657,  657,  657,  657,  122,
      657,  641,  657,  133,  145,  153,  151,  657,  657,  657,
      152,  657,  130,  139,  147,  151,  159,  160,  162,  165,

      168,  166,  167,  170,  169,  175,  171,  176,  177,  178,
      179,  182,  625,  183,  186,  192,  191,  194,  173,  196,
      207,  206,  208,  213,  212,  217,  221,  218,  225,  223,
      222,  228,  229,  230,  231,  657,  657,  657,  657,  657,
      657,  639,  657,  240,  623,  622,  657,  657,  657,  657,
      233,  236,  234,  254,  259,  263,  239,  244,  261,  264,
      267,  265,  268,  269,  271,  273,  274,  276,  278,  283,
      285,  621,  284,  280,  286,  291,  293,  300,  301,  620,
      302,  304,  303,  307,  310,  312,  313,  314,  315,  316,
      319,  322,  323,  317,  328,  619,  330,  618,  337,  326,

      327,  335,  329,  339,  347,  617,  616,  351,  615,  353,
      357,  358,  359,  360,  362,  363,  361,  614,  613,  366,
      364,  369,  365,  367,  371,  612,  373,  372,  382,  374,
      611,  375,  610,  395,  397,  398,  384,  376,  379,  402,
      405,  410,  411,  609,  380,  413,  608,  415,  607,  416,
      417,  606,  419,  423,  605,  604,  603,  602,  418,  420,
      421,  428,  601,  434,  425,  436,  600,  426,  599,  427,
      429,  437,  439,  453,  446,  449,  455,  457,  458,  456,
      598,  459,  597,  460,  461,  464,  465,  469,  474,  596,
      468,  475,  476,  477,  478,  595,  594,  593,  481,  483,

      487,  489,  592,  490,  491,  591,  495,  497,  496,  590,
      589,  588,  578,  498,  577,  500,  576,  502,  501,  575,
      510,  508,  574,  573,  572,  514,  515,  518,  519,  571,
      570,  520,  521,  522,  527,  568,  567,  566,  563,  528,
      529,  531,  537,  540,  532,  562,  541,  542,  558,  556,
      544,  555,  553,  551,  548,  550,  549,  657,  597,  599,
      601,  141,   98,  603
    } ;

static yyconst short int yy_def[365] =
    {   0,
      358,    1,  359,  359,  360,  360,  361,  361,  358,  358,
      358,  358,  358,  358,  362,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  362,  363,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  364,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  362,  362,  362,  362,  362,  362,  362,  362,

      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  358,  358,  358,  358,  358,
      358,  364,  358,  358,  358,  358,  358,  358,  358,  358,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,

      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,

      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,    0,  358,  358,
      358,  358,  358,  358
    } ;

static yyconst short int yy_nxt[715] =
    {   0,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   33,   15,   34,   10,   35,   36,   37,
       38,   39,   40,   41,   42,   43,   15,   44,   15,   45,
       15,   46,   15,   47,   48,   49,   50,   15,   51,   52,
       15,   15,   15,   53,   54,   55,   56,   58,   58,   61,
       72,   65,   61,   66,   76,   62,   59,   59,   62,   65,
       74,   66,   78,   77,   73,   87,   88,   81,   70,   79,
       75,   70,   82,   63,   70,   67,   63,   83,   84,   70,
       85,   90,   91,   67,   93,   70,   70,   86,   70,   70,

      101,   97,   70,   94,  102,   95,   86,   70,   98,  103,
       70,   99,   96,   70,  100,   70,  136,  104,  123,  105,
       70,  112,  107,  116,   70,  132,  129,  117,  106,   70,
      108,  118,  109,   70,  130,  110,  120,  113,  133,   80,
      111,  131,   69,  114,  115,  119,   86,   70,  124,  137,
      144,  121,  134,  135,  122,   86,   70,   86,  125,  126,
       84,  127,   85,  128,   70,  145,   86,  145,   70,   86,
      146,  147,  148,  149,  150,  151,   70,   70,   86,   70,
      153,  152,   70,   70,   70,   70,   70,   70,   70,  157,
       70,  158,   70,   70,   70,   70,   70,  154,  160,   70,

       70,  163,  161,   70,  155,  156,  159,  162,   70,   70,
      169,   70,  181,   70,  164,  165,  166,  170,  167,  171,
      173,  168,  172,   70,   70,   70,  175,  182,  174,   70,
       70,  176,  177,  178,   70,   70,  185,  179,   70,   70,
       70,  188,   70,  180,  183,   70,   70,   70,   70,  184,
       70,   70,  194,   70,  186,  187,   70,  144,  190,  191,
      189,   70,  192,  205,   86,  197,  199,  201,  200,  193,
      195,   70,  198,   86,  196,  204,   70,  202,   70,  203,
       70,   70,   70,  209,   70,   70,   70,  206,   70,  210,
       70,   70,  207,   70,  208,   70,  214,   70,  215,  217,

       70,   70,   70,   70,  218,  216,  211,  212,   70,  221,
       70,  213,  223,  219,  224,  225,  220,   70,   70,   70,
       70,   70,  226,  222,   70,  227,  230,   70,  228,   70,
       70,   70,   70,   70,   70,  231,   70,  229,  232,   70,
       70,  233,  234,   70,   70,   70,   70,   70,  241,  237,
      243,  235,   70,  236,   70,  250,   70,  239,  246,  238,
      240,  247,  242,  248,   70,  245,  251,  244,   70,  249,
       70,  252,  254,  253,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,  255,   70,  256,   70,   70,
       70,   70,   70,   70,  260,  259,   70,   70,  257,   70,

      264,   70,  267,  258,  268,  266,  271,  261,  262,  263,
      265,  273,   70,  269,   70,   70,  272,  270,  274,   70,
      280,  279,   70,  275,  276,  281,  277,   70,   70,  286,
       70,  278,   70,   70,   70,   70,   70,   70,   70,  282,
       70,  284,   70,   70,   70,   70,   70,  285,  291,  283,
      290,   70,  292,   70,   70,  294,   70,  288,  287,  293,
      295,  296,  289,   70,  301,  300,   70,  297,  299,  302,
       70,  298,   70,   70,   70,   70,   70,   70,   70,  306,
      304,   70,   70,  303,  307,   70,   70,  305,  309,  310,
      312,   70,   70,   70,   70,   70,  313,  311,   70,  319,

       70,  308,  316,  317,   70,  314,   70,   70,   70,  315,
      322,  318,   70,   70,   70,   70,  320,   70,   70,   70,
      329,  328,  327,  321,  323,   70,  324,   70,  330,  326,
      331,   70,   70,  334,  325,   70,   70,   70,   70,   70,
      333,  335,  332,  337,   70,   70,   70,  336,   70,   70,
      342,  341,  338,  343,   70,  339,  340,   70,   70,   70,
      346,   70,  344,  345,  349,   70,   70,   70,   70,  350,
       70,  348,   70,   70,  347,   70,  354,  351,  352,   70,
       70,  356,  357,   70,   70,   70,  353,   70,   70,   70,
       70,   70,   70,   70,   70,   70,  355,   57,   57,   60,

       60,   64,   64,  142,  142,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,  146,
      146,  143,   70,  143,  141,   70,  140,  139,  138,   92,
       89,   80,   71,   70,   68,  358,    9,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,

      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358
    } ;

static yyconst short int yy_chk[715] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    4,    5,
       17,    7,    6,    7,   22,    5,    3,    4,    6,    8,
       21,    8,   24,   22,   17,   30,   30,   26,   38,   24,
       21,   37,   26,    5,   40,    7,    6,   26,   27,   39,
       27,   32,   32,    8,   37,   41,   43,   27,   45,  363,

       40,   39,   48,   38,   40,   38,   27,   50,   39,   40,
       42,   39,   38,   51,   39,   46,   54,   41,   48,   41,
       44,   43,   42,   45,   47,   51,   50,   46,   41,   49,
       42,   46,   42,   52,   50,   42,   47,   44,   51,   80,
       42,   50,  362,   44,   44,   46,   80,   93,   49,   54,
       84,   47,   52,   52,   47,   80,   94,   84,   49,   49,
       85,   49,   85,   49,   95,   86,   84,   86,   96,   85,
       86,   87,   87,   91,   91,   93,   97,   98,   85,   99,
       95,   94,  100,  102,  103,  101,  105,  104,  107,   98,
      119,   99,  106,  108,  109,  110,  111,   96,  101,  112,

      114,  102,  101,  115,   97,   97,  100,  101,  117,  116,
      107,  118,  119,  120,  103,  104,  105,  108,  106,  109,
      111,  106,  110,  122,  121,  123,  114,  120,  112,  125,
      124,  115,  115,  116,  126,  128,  122,  117,  127,  131,
      130,  125,  129,  118,  121,  132,  133,  134,  135,  121,
      151,  153,  130,  152,  123,  124,  157,  144,  127,  128,
      126,  158,  129,  153,  144,  131,  133,  134,  133,  129,
      130,  154,  132,  144,  130,  152,  155,  135,  159,  151,
      156,  160,  162,  157,  161,  163,  164,  154,  165,  158,
      166,  167,  155,  168,  156,  169,  161,  174,  162,  164,

      170,  173,  171,  175,  165,  163,  159,  159,  176,  168,
      177,  160,  170,  166,  171,  173,  167,  178,  179,  181,
      183,  182,  174,  169,  184,  175,  177,  185,  175,  186,
      187,  188,  189,  190,  194,  178,  191,  176,  179,  192,
      193,  181,  182,  200,  201,  195,  203,  197,  189,  185,
      191,  183,  202,  184,  199,  200,  204,  187,  194,  186,
      188,  195,  190,  197,  205,  193,  201,  192,  208,  199,
      210,  202,  204,  203,  211,  212,  213,  214,  217,  215,
      216,  221,  223,  220,  224,  205,  222,  208,  225,  228,
      227,  230,  232,  238,  213,  212,  239,  245,  210,  229,

      217,  237,  222,  211,  223,  221,  227,  214,  215,  216,
      220,  229,  234,  224,  235,  236,  228,  225,  230,  240,
      238,  237,  241,  232,  234,  239,  235,  242,  243,  245,
      246,  236,  248,  250,  251,  259,  253,  260,  261,  240,
      254,  242,  265,  268,  270,  262,  271,  243,  253,  241,
      251,  264,  254,  266,  272,  260,  273,  248,  246,  259,
      261,  262,  250,  275,  270,  268,  276,  264,  266,  271,
      274,  265,  277,  280,  278,  279,  282,  284,  285,  275,
      273,  286,  287,  272,  276,  291,  288,  274,  278,  279,
      282,  289,  292,  293,  294,  295,  284,  280,  299,  291,

      300,  277,  287,  288,  301,  285,  302,  304,  305,  286,
      294,  289,  307,  309,  308,  314,  292,  316,  319,  318,
      305,  304,  302,  293,  295,  322,  299,  321,  307,  301,
      308,  326,  327,  316,  300,  328,  329,  332,  333,  334,
      314,  318,  309,  321,  335,  340,  341,  319,  342,  345,
      329,  328,  322,  332,  343,  326,  327,  344,  347,  348,
      335,  351,  333,  334,  342,  355,  357,  356,  354,  343,
      353,  341,  352,  350,  340,  349,  348,  344,  345,  346,
      339,  355,  356,  338,  337,  336,  347,  331,  330,  325,
      324,  323,  320,  317,  315,  313,  351,  359,  359,  360,

      360,  361,  361,  364,  364,  312,  311,  310,  306,  303,
      298,  297,  296,  290,  283,  281,  269,  267,  263,  258,
      257,  256,  255,  252,  249,  247,  244,  233,  231,  226,
      219,  218,  209,  207,  206,  198,  196,  180,  172,  146,
      145,  142,  113,   82,   74,   69,   67,   63,   59,   36,
       31,   25,   16,   15,   13,    9,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,

      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
#line 1 "lexic.l"
#define INITIAL 0
#line 2 "lexic.l"
	//Defines and includes
	#include "parse.cpp.h"
	#include "KurCommon.h"
	#include <io.h>

	#include <malloc.h>
	#include <stdarg.h>

	#define YY_NO_UNISTD_H
#define long_comment 1

#define const_string1 2

#define const_string2 3

#line 28 "lexic.l"
	//yytext : a character array that contains the actual string that matched a pattern.
	//yyleng : the no. of characters matched.
	
	YYSTATPOS g_yypos;
	
	// update global position
	#define UP 		g_yypos.incLinePos(yyleng);
	
	// update position after new line
	#define UPNL 	g_yypos.getLine();
	
#line 670 "lexic.cpp"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 41 "lexic.l"


#line 820 "lexic.cpp"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 359 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 657 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 43 "lexic.l"
/* integer number */ {
	UP	return INT_NUM;
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 47 "lexic.l"
/* Float number */ {
UP

return LITERAL_NUMBER;
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 56 "lexic.l"
/* Const string */	{ UP BEGIN(const_string1); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 57 "lexic.l"
/* Const string */	{ UP BEGIN(const_string2); }
	YY_BREAK


case 5:
YY_RULE_SETUP
#line 61 "lexic.l"
{ UP BEGIN(0); return CSTRING; 							}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 62 "lexic.l"
{ UP /* escape character*/								}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 63 "lexic.l"
{ UPNL; yyerror("Next line but no end ' symbol found\n"); 	}
	YY_BREAK
case YY_STATE_EOF(const_string1):
#line 64 "lexic.l"
{ yyerror("EOF but no end ' symbol found\n"); 				}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 65 "lexic.l"
{ UP /*ignore*/ 											}
	YY_BREAK



case 9:
YY_RULE_SETUP
#line 70 "lexic.l"
{ UP BEGIN(0); return CSTRING;							}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 71 "lexic.l"
{ UP /* escape character*/								}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 72 "lexic.l"
{ UPNL; yyerror("Next line but no end \" symbol found\n");	}
	YY_BREAK
case YY_STATE_EOF(const_string2):
#line 73 "lexic.l"
{ yyerror("EOF but no end \" symbol found\n");				}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 74 "lexic.l"
{ UP /*ignore*/ 											}
	YY_BREAK

case 13:
YY_RULE_SETUP
#line 79 "lexic.l"
/* Comments: single line comment */ {
UPNL;  
/* ignore */
}	
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 84 "lexic.l"
/* Comments: multiple line comment */ { UP BEGIN(long_comment); }
	YY_BREAK


case 15:
YY_RULE_SETUP
#line 88 "lexic.l"
{ UP BEGIN(0); 								}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 89 "lexic.l"
{ UPNL; 										}
	YY_BREAK
case YY_STATE_EOF(long_comment):
#line 90 "lexic.l"
{ yyerror("EOF but no end */ symbol found\n");	}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 91 "lexic.l"
{ UP /*ignore*/ 								}
	YY_BREAK

case 18:
YY_RULE_SETUP
#line 97 "lexic.l"
/* JZ reserved word */ 	{ UP return ABSTRACT; 	}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 98 "lexic.l"
/* JZ reserved word */	{ UP return BOOLEAN; 		}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 99 "lexic.l"
/* JZ reserved word */  { UP return BREAK; 		}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 100 "lexic.l"
/* JZ reserved word */  { UP return BYTE; 		}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 101 "lexic.l"
/* JZ reserved word */  { UP return CASE; 		}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 102 "lexic.l"
/* JZ reserved word */  { UP return CATCH; 		}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 103 "lexic.l"
/* JZ reserved word */  { UP return CHAR; 		}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 104 "lexic.l"
/* JZ reserved word */  { UP return CLASS; 		}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 105 "lexic.l"
/* JZ reserved word */  { UP return CONST; 		}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 106 "lexic.l"
/* JZ reserved word */  { UP return CONTINUE; 	}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 107 "lexic.l"
/* JZ reserved word */  { UP return DEBUGGER; 	}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 108 "lexic.l"
/* JZ reserved word */  { UP return DEFAULT; 		}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 109 "lexic.l"
/* JZ reserved word */  { UP return DELETE; 		}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 110 "lexic.l"
/* JZ reserved word */  { UP return DO; 			}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 111 "lexic.l"
/* JZ reserved word */  { UP return DOUBLE; 		}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 112 "lexic.l"
/* JZ reserved word */  { UP return ELSE; 		}	
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 113 "lexic.l"
/* JZ reserved word */  { UP return ENUM; 		}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 114 "lexic.l"
/* JZ reserved word */  { UP return EXPORT; 		}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 115 "lexic.l"
/* JZ reserved word */  { UP return EXTENDS; 		}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 116 "lexic.l"
/* JZ reserved word */  { UP return FALSE; 		}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 117 "lexic.l"
/* JZ reserved word */  { UP return FINAL; 		}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 118 "lexic.l"
/* JZ reserved word */  { UP return FINALLY; 		}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 119 "lexic.l"
/* JZ reserved word */  { UP return FLOAT; 		}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 120 "lexic.l"
/* JZ reserved word */  { UP return FOR; 			}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 121 "lexic.l"
/* JZ reserved word */  { UP return FUNCTION; 	}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 122 "lexic.l"
/* JZ reserved word */  { UP return GOTO; 		}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 123 "lexic.l"
/* JZ reserved word */  { UP return IF; 			}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 124 "lexic.l"
/* JZ reserved word */  { UP return IMPLEMENTS; 	}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 125 "lexic.l"
/* JZ reserved word */  { UP return IMPORT; 		}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 126 "lexic.l"
/* JZ reserved word */  { UP return IN; 			}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 127 "lexic.l"
/* JZ reserved word */  { UP return INSTANCEOF; 	}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 128 "lexic.l"
/* JZ reserved word */  { UP return INT; 			}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 129 "lexic.l"
/* JZ reserved word */  { UP return INTERFACE; 	}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 130 "lexic.l"
/* JZ reserved word */  { UP return LONG; 		}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 131 "lexic.l"
/* JZ reserved word */  { UP return NATIVE; 		}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 132 "lexic.l"
/* JZ reserved word */  { UP return NEW; 			}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 133 "lexic.l"
/* JZ reserved word */  { UP return NUL; 			}	
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 134 "lexic.l"
/* JZ reserved word */  { UP return PACKAGE; 		}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 135 "lexic.l"
/* JZ reserved word */  { UP return PRIVATE; 		}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 136 "lexic.l"
/* JZ reserved word */  { UP return PROTECTED; 	}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 137 "lexic.l"
/* JZ reserved word */  { UP return PUBLIC; 		}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 138 "lexic.l"
/* JZ reserved word */  { UP return RETURN; 		}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 139 "lexic.l"
/* JZ reserved word */  { UP return SHORT; 		}	
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 140 "lexic.l"
/* JZ reserved word */  { UP return STATIC; 		}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 141 "lexic.l"
/* JZ reserved word */  { UP return SUPER; 		}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 142 "lexic.l"
/* JZ reserved word */  { UP return SWITCH; 		}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 143 "lexic.l"
/* JZ reserved word */  { UP return SYNCHRONIZED; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 144 "lexic.l"
/* JZ reserved word */  { UP return THIS; 		}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 145 "lexic.l"
/* JZ reserved word */  { UP return THROW; 		}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 146 "lexic.l"
/* JZ reserved word */  { UP return THROWS; 		}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 147 "lexic.l"
/* JZ reserved word */  { UP return TRANSIENT;	}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 148 "lexic.l"
/* JZ reserved word */  { UP return TRUE; 		}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 149 "lexic.l"
/* JZ reserved word */  { UP return TRY; 			}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 150 "lexic.l"
/* JZ reserved word */  { UP return TYPEOF; 		}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 151 "lexic.l"
/* JZ reserved word */  { UP return VAR; 			}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 152 "lexic.l"
/* JZ reserved word */  { UP return VOID; 		}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 153 "lexic.l"
/* JZ reserved word */  { UP return VOLATILE; 	}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 154 "lexic.l"
/* JZ reserved word */  { UP return WHILE; 		}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 155 "lexic.l"
/* JZ reserved word */  { UP return WITH; 		}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 160 "lexic.l"
/* Variable/function name */ {
UP	return OBJ_NAME;
}
	YY_BREAK
case 78:
#line 167 "lexic.l"
case 79:
#line 168 "lexic.l"
case 80:
YY_RULE_SETUP
#line 168 "lexic.l"
{ UP return OPL_NOT; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 169 "lexic.l"
{ UP return OPL_AND; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 170 "lexic.l"
{ UP return OPL_OR; 	}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 171 "lexic.l"
{ UP return OPL_L; 	}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 172 "lexic.l"
{ UP return OPL_G; 	}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 173 "lexic.l"
{ UP return OPL_LE; 	}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 174 "lexic.l"
{ UP return OPL_GE; 	}
	YY_BREAK
case 87:
#line 177 "lexic.l"
case 88:
#line 178 "lexic.l"
case 89:
YY_RULE_SETUP
#line 178 "lexic.l"
{ UP return OP_ASSIGN_ADD; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 179 "lexic.l"
{ UP return OP_ASSIGN_SUB; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 180 "lexic.l"
{ UP return OP_ASSIGN_POW; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 181 "lexic.l"
{ UP return OP_ASSIGN_MUL; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 182 "lexic.l"
{ UP return OP_ASSIGN_DIV; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 183 "lexic.l"
{ UP return OP_ASSIGN_MOD; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 184 "lexic.l"
{ UP return OP_ASSIGN_AND; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 185 "lexic.l"
{ UP return OP_ASSIGN_OR; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 186 "lexic.l"
{ UP return OP_ASSIGN_XOR; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 187 "lexic.l"
{ UP return OP_ASSIGN; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 189 "lexic.l"
{ UP return OPB_NOT; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 190 "lexic.l"
{ UP return OPB_OR;  }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 191 "lexic.l"
{ UP return OPB_AND; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 192 "lexic.l"
{ UP return OPB_XOR; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 193 "lexic.l"
{ UP return OPB_LSHIFT; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 194 "lexic.l"
{ UP return OPB_RSHIFT; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 196 "lexic.l"
{ UP return OPA_INC; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 197 "lexic.l"
{ UP return OPA_DEC; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 198 "lexic.l"
{ UP return OPA_MUL; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 199 "lexic.l"
{ UP return OPA_DIV; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 200 "lexic.l"
{ UP return OPA_MOD; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 201 "lexic.l"
{ UP return OPA_ADD; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 202 "lexic.l"
{ UP return OPA_SUB; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 204 "lexic.l"
{ UP return DOT; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 205 "lexic.l"
{ UP return COMA; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 206 "lexic.l"
{ UP return COLON; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 207 "lexic.l"
{ UP return QMARK; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 208 "lexic.l"
{ UP return LBRACKET_ROUND; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 209 "lexic.l"
{ UP return RBRACKET_ROUND; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 210 "lexic.l"
{ UP return LBRACKET_SQUARE;}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 211 "lexic.l"
{ UP return RBRACKET_SQUARE;}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 212 "lexic.l"
{ UP return LBRACKET_CURLY; }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 213 "lexic.l"
{ UP return RBRACKET_CURLY; }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 216 "lexic.l"
/* Spaces: tab and space */ {
UP	
}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 220 "lexic.l"
/* Spaces: operation splitter */ {
	//g_yystat.yystartpos = g_yystat.yyglobalpos;
	return END_OP;
}
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 225 "lexic.l"
/* Spaces: newline */ {
UPNL;
}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 229 "lexic.l"
/* Lex error */  {
	
	yyerror("Unexpected symbol '%c'\n", yytext[0]);
}
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 234 "lexic.l"
ECHO;
	YY_BREAK
#line 1563 "lexic.cpp"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 359 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 359 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 358);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int _isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (_isatty( _fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 234 "lexic.l"


//void yyLexInit() 
//{	
//	g_yystat.yyline = 1;
//	g_yystat.yylinepos = 0;
//	g_yystat.yyglobalpos = 0;
//	g_yystat.yystartpos = 0;
//}


void yyerror(const char* format, ...)
{
	// retrieve the variable arguments and print
	va_list args;  
    va_start( args, format );  
	vprintf(format, args);
	
	if (!strcmp(format, "parse error"))
		printf("\n");
	
	std::cout << "Error position: Line " << g_yypos.getLine() << ", Column " << g_yypos.getCol() << std::endl;

	//printf("Position: [line %u: %u]\n", g_yystat.yyline, g_yystat.yylinepos);
	//printf("Text: '%s'\n", yytext);
	
	//yyin.close();
	//yyLexCleanup();
	//yyYaccCleanup();
	
	//WAIT_USER;
	//exit(1);
}

//void yyLexCleanup() {}
